backend:
  name: github
  repo: RuslanOnoprienko2025/seo-content-hub
  branch: main
  base_url: https://seo-content-hub-v2.pages.dev
  auth_endpoint: auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Статьи"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата (для порядка)", name: "date", widget: "datetime", required: false}
      - label: "Шаблон"
        name: "layout"
        widget: "select"
        options:
          - {label: "Guide", value: "../../layouts/Guide.astro"}
          - {label: "Comparison", value: "../../layouts/Comparison.astro"}
          - {label: "Post", value: "../../layouts/Layout.astro"}
      - {label: "Обложка", name: "image", widget: "image", required: false}
      - {label: "Показывать обложку в статье?", name: "show_image", widget: "boolean", default: true}
      - {label: "SEO Title (для поиска)", name: "seo_title", widget: "string", required: false }
      - {label: "SEO Description", name: "description", widget: "text"}
      - {label: "Текст статьи", name: "body", widget: "markdown"}
      - label: "Проект (Домен)"
        name: "project"
        widget: "select"
        options:
          - {label: "JPG to WebP (.onl)", value: "jpg-to-webp"}
          - {label: "PNG to WebP (.online)", value: "png-to-webp"}
          - {label: "WebP to PNG (.xyz)", value: "webp-to-png"}
          - {label: "WebP to JPG (.pro)", value: "webp-to-jpg"}
          - {label: "PNG to JPG (.pics)", value: "png-to-jpg"}
          - {label: "JPG to PNG (.help)", value: "jpg-to-png"}
          - {label: "Email Signatures (.xyz)", value: "signatures"}
